backend:
  name: github
  branch: main

collections:
  - name: modules
    label: Training Modules
    folder: docs/*/index.md
    create: true
    slug: "{{module}}"
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: libdoc/page
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Category
        name: category
        widget: select
        options: ["Training Modules"]
        default: "Training Modules"
      - label: Order
        name: order
        widget: number
        default: 1
      - label: Module Type
        name: moduleType
        widget: select
        options: ["Technical", "Non-Technical"]
      - label: Body
        name: body
        widget: markdown

  - name: levels
    label: Module Levels
    folder: docs/*/level-*.md
    create: true
    slug: "{{module}}/level-{{level}}"
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: libdoc/page
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Level
        name: level
        widget: number
        min: 1
        max: 4
      - label: Prerequisites
        name: prerequisites
        widget: list
        required: false
      - label: Learning Objectives
        name: objectives
        widget: list
        required: true
      - label: Resources
        name: resources
        widget: list
        required: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: URL, name: url, widget: string}
      - label: Body
        name: body
        widget: markdown

  - name: pages
    label: Site Pages
    files:
      - label: Home
        name: home
        file: index.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: libdoc/page
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
          - label: Category
            name: category
            widget: string
          - label: Order
            name: order
            widget: number
          - label: Body
            name: body
            widget: markdown

      - label: Curriculum Overview
        name: curriculum
        file: curriculum.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: libdoc/page
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
          - label: Body
            name: body
            widget: markdown

media_folder: assets/images
public_folder: /assets/images

site_url: https://fletch3555.github.io/3181-training-program
display_url: https://fletch3555.github.io/3181-training-program
logo_url: /assets/images/logo.png