content:
- name: modules
  type: collection
  path: docs/*/index.md
  fields:
    - name: string
      description: text
    - name: category
      type: select
      options:
        values:
          - Training Modules
      default: Training Modules
    - name: order
      type: number
    - name: moduleType
      type: select
      options:
        values: 
        - Technical
        - Non-Technical
    - name: layout
      type: string
      default: libdoc/page
      hidden: true

- name: levels
  type: collection
  path: docs/*/level-*.md
  fields:
    - name: title
      type: string
      description: text
    - name: module
      label: Module
      type: reference
      options:
        collection: modules
    - name: level
      type: number
      options:
        min: 1
        max: 4
    - name: prerequisites
      label: Prerequisites
      type: reference
      options:
        collection: levels
        multiple: true
    - name: objectives
      type: string
      list: true
      required: true
    - name: resources
      type: object
      list: true
      required: false
      fields:
        - name: title
          type: string
        - name: url
          type: string
    - name: layout
      type: string
      default: libdoc/page
      hidden: true

media:
  input: assets/images
  output: /assets/images