name: Pages CMS

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  pages-cms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Deploy Pages CMS
        uses: pages-cms/action@v0.0.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}